version: "3.9"
services:
  linuxbox:
    container_name: fuse-win-blob
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8500:8500"
    environment:
      - AZURE_STORAGE_ACCOUNT=xxxxxxxxxx
      - AZURE_STORAGE_ACCESS_KEY=xxxxxxxxxxxxxxxxxxx
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - /blobs:/blobs:rw,rshared